### ISSUE TITLE
三体之地球往事

### ISSUE THREAD

**Issue by SunShinewyf** [SunShinewyf/issue-blog#11]
![images](https://raw.githubusercontent.com/SunShinewyf/issue-blog/master/assets/books/9.jpg)

之前一直听说这本书很出色，朋友也是力推这本书，于是就下载了电子版的三部曲，真正看下去之后，就不能自拔了，这本书确实写得很精彩，如果没有一定的科学方面的知识和人文方面的素养，是绝不会有这样的著作的。在首页的导读中，姚海军写到：
> 中国科幻与美国科幻的差距。在科幻作品方面，中国虽然需求很大，但是可以摆在市面上的作品确是寥寥无几。

但是刘慈欣的这部作品确是给中国的科幻作品添上了浓墨重彩的一笔，值得赞叹和喝彩。

实习的生活还是比较忙的，而且我也不想贪恋着一口气读完，所以一般是利用早上挤地铁的时候来欣赏一下，看到动情处，总是感叹作者的想象力和文笔，惊叹这么浩渺磅礴的场景描述。

第一部的主人公是汪淼，一个研究纳米材料的教授。却被卷入一场阴谋当中，一个处于地球之外的三体文明，策划着一场即将侵蚀和禁锢地球文明的阴谋。故事在一开始是很悬疑的，汪淼被一个诡异的倒计时折磨着，就像幽灵，在他所在之处跳跃着。

这种感觉，让人害怕和惊悚。之后，杨冬和一些著名科学家的死更加增添了这层诡异。汪淼在三体世界这个游戏中体验的一些三体世界的生活更是让人惊讶。人可以在乱纪元中脱水储藏，在恒纪元中浸泡让自己复活，这种`“异想天开”`的想象让我佩服，这种因为自然环境的因素而演化出来的存活和死亡，居然是这样地神奇。随着汪淼在三体游戏玩的次数越来越多，故事的真相也在慢慢揭晓。最后水落石出是叶文洁说出来的
> 自己在红岸基地上研究，并且向三体文明发出了地球文明的回应，除此之外，她还亲手杀了她的丈夫杨卫宁和一名军官雷志成。最后伊文斯知道了叶文洁的秘密之后，居然建立了地球上的三体组织，他们把三体文明奉为主，并且在地球上建立起拥护三体文明的组织，并通过这个组织不断地向远在地球之外的三体人发送着地球上一切。这还不算什么，在从伊文斯被截断的船上获取最新的他们和三体人的最后一次交流中可以获知，三体人已经研发出一种叫做"质子"的东西，它可以监视地球上的一举一动，阻碍地球上的物理学领域的发展，甚至因此让地球上一些出色的科学家在精神上迷乱甚至因此自杀，只有这样，地球上的科学才会停滞不前。

戳穿了三体人民的阴谋之后，一切都真相大白了。但是面对如此强大的敌人，地球人显得手足无措甚至恐慌，这太不可思议了，在宇宙之中，居然还存在着除了地球文明之外的文明，并且这个文明即将毁灭地球文明。知道真相的汪淼和丁仪感到很挫败，

甚至产生了失败主义，他们不知道怎么去对付这个强大的质子和三体文明的入侵，但是大史带着他们去他家乡看蝗虫的繁衍，将人和蝗虫之间的对峙和人与三体人民的对峙进行对比
> “是地球人和三体人的技术水平差距大呢，还是蝗虫和咱们人的技术水平差距大？”

这句话让汪淼和丁仪顿时自惭形秽，于是第一部就在这种未知胜负的结局中结束了。。。
看完第一部之后，真的很震撼，这部书中，充满着很多的物理知识以及一些其他领域的知识，比如宇宙领域的，文学领域的，三体游戏中出现的各种场景，不论是中国历史还是外国历史，作者都很熟悉并很自然地结合自己的想象力揉在字里行间中，简直是太神奇了。看完之后很赞叹。

故事的帷幕在一点点拉开，期待和第二部的相见。。。。。

**Comment by chenshenhai** [comment]
哈哈，记得书里面有句话`“给岁月以文明，而不是给文明以岁月”`让人意犹未尽

**Comment by SunShinewyf** [comment]
嗯嗯，是一种高层次科技文明的精神碰撞
