### ISSUE TITLE
孤独六讲

### ISSUE THREAD

**Issue by SunShinewyf** [SunShinewyf/issue-blog#25]
![images](https://raw.githubusercontent.com/SunShinewyf/issue-blog/master/assets/books/18.jpg)

很少涉猎哲学和思辨的书，总觉得是在玩文字游戏而且字里行间随处可见枯燥。这本书确实出乎我意料，不仅文笔优美，又有理有据，结合古今中外的事例，将一种无形而又伟大的孤独感描述得可触可感，真实存在而又不晦涩难懂。让人拍案叫好的同时又不得不心悦诚服。
书中主要讲了6种孤独：
- 情欲孤独
- 语言孤独
- 革命孤独
- 暴力孤独
- 思维孤独
- 伦理孤独

在每一种孤独中，作者不仅阐述着自己的见解、亲身经历，还结合一些名著、现实中的事例加以佐证。原本以为，孤独无非是夜深人静，独自一人，在郁结于心的难受时刻无人倾述的一种可怜。然而读罢全书，才明白我的思想过于狭隘了。孤独分为很多种，除此之外，孤独并不意味着寂寞，相反享受孤独的人，才会更加懂得透过自己的灵魂看世界。在现实生活的我们，常常叫嚣着要摆脱孤独，于是将自己置身于闹市、琴瑟和鸣的处境中，然而却发现随之而来的却是更大的孤独感。

> 孤独并非寂寞孤独和寂寞不一样。寂寞会发慌，孤独则是饱满的，是庄子说的「独与天地精神往来」，是确定生命与宇宙间的对话，已经到了最完美的状态。

伟大的人都是孤独的，如项羽，如屈原，亦如高渐离，这些人用自己的生命诠释着孤独如史诗般绚烂的最高境界。让读者不再猥亵孤独，不是对孤独的人投以同情的一瞥，而是以一种虔诚、仰望的姿态去尊敬他们、敬仰他们。伟大的人都是孤独的，只有在孤独中，他们才能真正知道自己内心深处的诉求并为之追求一生，不惜牺牲自己的生命。

孤独的人注定是要受到争议的，“永远也不要做第一个人和最后一个人”，这句话足以说明现在的人更愿意随波逐流而不是特立独行，不合群的人注定会受到排挤，众口铄金的现实使得我们都随着大流，隐忍着自己内心最真实的追求。于是，在我们活得都想是社会的复制品的时候，我们也就不再是最初的那个自己了。

对于孤独，我们永远排斥，孤独意味着清冷、落寞，于是很多人都去逃避孤独或者去追随其他东西从而来填满自己的孤独感。然而，孤独是自己和自己的一种对话。

> 有时候你会发现，速度与深远似乎是冲突的，当你可以和自己对话，慢慢地储蓄一种情感、酝酿一种情感时，你便不再孤独；而当你不能这么做时，永远都在孤独的状态，你跑得愈快，孤独追得愈紧，你将不断找寻柏拉图寓言中的另外一半，却总是觉得不对；即使最后终于找到「对的」另外一半，也失去耐心，匆匆就走了。

> 我更相信，我们心灵一旦不再那么慌张地去乱抓人来填补寂寞，我们会感觉到饱满的喜悦，是狂喜，是一种狂喜。就像气球，被看起来什么都没有的气体充满，整个心灵也因为孤独而鼓胀了起来，此时便能感觉到生命的圆满自足。孤独圆满，思维得以发展。

孤独并不可怕，可怕的是我们从来不愿意给自己留丝毫孤独对话的空间，然而现在快节奏的社会里，越来越多的人宁愿选择和几个陌生人一起尬聊，也不愿意真实地面对自己。

>生命里第一个爱恋的对象应该是自己，写诗给自己，与自己对话，在一个空间里安静下来，聆听自己的心跳与呼吸，我相信，这个生命走出去时不会慌张

> 所以我说孤独是一种福气，怕孤独的人就会寂寞，愈是不想处于孤独的状态，愈是去碰触人然后放弃，反而会错失两千年来你寻寻觅觅的另一半。有时候我会站在忠孝东路边，看着人来人往，觉得城市比沙漠还要荒凉，每个人都靠得那么近，但完全不知彼此的心事，与孤独处在一种完全对立的位置，那是寂寞。

学会享受孤独，才能体会到一种精神食粮的真实存在。

**Comment by QGB** [comment]
寂寞难耐
