### ISSUE TITLE
月亮和六便士

### ISSUE THREAD

**Issue by SunShinewyf** [SunShinewyf/issue-blog#26]
![images](https://raw.githubusercontent.com/SunShinewyf/issue-blog/master/assets/books/19.jpg)

说实话，刚看第一章的时候我是觉得很恶心的，因为除了各种赞美和夸耀之类的词之外，就是各种无厘头的描述，让人摸不着头脑，不仅没有先抑后扬的技巧，也没有比较新奇的铺陈，一来就是各种夸大形象的“陈词滥调”，让我觉得很反感，而且看这本书之前也没有想到是写人物传记的，然而坚持到第二章甚至更后一点，就开始慢慢被吸引了。。。

整本书的内容都是围绕查理斯.思特里克兰德而展开的，从作者到刚开始和他有交集到和他初识并亲眼见证过他落魄的几年，最后一直到从他人口中得知主人公的晚年生活到病逝的全过程，给读者塑造了一个伟大而怪异的画家天才形象。文笔平实简单而又不显得啰嗦冗余，作者以一个中立的旁观者的形象，见证了一个伟人的诞生和最终被全世界认可的神奇之旅。

说实话，对“伟人”这个概念也只是有一种比较模糊的印象，总觉得或者有几分被神化的成分在，也比较少接触到一些个人传记的书籍，所以也无从对比来评判这本书何其优劣。但是整体上还是比较吸引我的，至少是从作者亲身经历，亲眼所见、所感而展现出来的形象，所以便少了几分质疑的心理因素。这本书最吸引我的应该是比较详尽的叙事部分，通过描述事件的发生经历来展示人物的性格魅力，让读者在细节之处领略人物精神上的伟大。

说实话，和作者一样，刚开始对思特里克兰德的印象还是不怎么看好的，总觉得比较自私、冷漠而又怪异，这或者就是天才和平凡人之间的显著差别吧（精神层次无法达到，捂脸）。思特克兰德在四十岁的时候放弃了比较优渥的证券经纪人的生活，在所有人都不解的情形之下抛家弃子，独自一人开始了追求画画的生涯，所有人都以为思特里克兰德是因为和其他女人去过享受的生活时，其实他却为了追求画画过着穷困潦倒的生活，差点贫困交加到饿死病死，最后在斯特略夫的帮助下得所幸免于难。让人没有想到的是，斯特略夫的妻子却因为他而背叛了自己的丈夫，甚至最后因情而死。之后的之后，思特里克兰德去了一个叫塔希提的小岛度过了比较幸福的晚年生活。

人的一生似乎看似漫长实则转瞬即逝，每个人对生活评判的幸福标准并不一样，比如有些人比较在意别人的眼光和言论，就会尽其所能地去活成一个好儿子、好公民、好丈夫。但是有的人就可以在精神层次上乐不思蜀，他们不会在意别人的眼光，只要自己活得舒坦和从容就是最大的满足，我很佩服这类人。思特里克兰德在这一点上尤其突出，他无视所有的一切，生活的舒适度、爱情、女人、性都没有成为他对创作执迷的羁绊，相反他却始终义无反顾地抛开这些东西而去追寻属于自己的精神之旅，当然，他成为了一个伟人。。。。

> 使思特里克兰德着了迷的是一种创作欲，他热切地想创造出美来，这种激情叫他一刻也不能宁静，逼着他东奔西走，他好像是一个终生跋涉的朝圣者，永远思慕着一块圣地，盘踞在他心头的魔鬼对他毫无怜悯之情。世上有些人渴望寻获真理，他们的要求非常强烈，为了达到这个目的，就是叫他们把生活的基础完全打翻，也在所不惜。

这就是思特里克兰德对创作执迷的真实写照了吧。

> 我们每个人生在世界上都是孤独的。每个人都被囚禁在一座铁塔里，只能靠一些符号同别人传达自己的思想；而这些符号并没有共同的价值，因此它们的意义是模糊的、不确定的。我们非常可怜地想把自己心中的财富传送给别人，但是他们却没有接受这些财富的能力。因此我们只能孤独的行走，尽管身体相互依傍却并不在一起，既不了解别的人也不能为别人所了解。

天才的人和其他人之间总有着一种难以逾越的鸿沟，他们不能相互理解，所以对于这类人来说，内心是非常孤独的。

最后以文中的一句话做总结：

> 上帝的磨盘转动很慢，但是却磨得很细。

每个人的生活都不一样，重要的不在乎长短，而是在这一段人生旅程里面，你是否活成了你想要的样子。。。

**Comment by truechuan** [comment]
666
