### ISSUE TITLE
巨人的陨落 II

### ISSUE THREAD

**Issue by SunShinewyf** [SunShinewyf/issue-blog#29]
![images](https://raw.githubusercontent.com/SunShinewyf/issue-blog/master/assets/books/20.jpg)

花一天时间看完了第二部，`巨人的陨落II` 主要是讲述了发动战争之后的一些事情，战争包括英德两国和俄德两国之间的战争，当然还有作为中立者的美国以及其他国家之间的战争。在这部中，一些主要的主人公都投入到战争当中，其中包括`比利・威廉姆斯`、`格雷戈里・别斯科夫`、`菲茨赫伯特伯爵`以及`沃尔特・冯・乌尔里希`。在几大国交战的过程中，他们在战争中的英勇表现以及对整个国家的影响牵动着整个故事的紧张。
  
在这部中，一些女主人公也表现出了自己坚强和向往自由的伟大精神，其中典型的就是`艾瑟尔・威廉姆斯`，虽然被爱的人抛弃，被父母逐出家门，但是她仍然在异国他乡坚强地战胜着一切生活赋予的苦难，不仅生下了可爱的儿子，儿子和`茉黛・菲茨赫伯特女勋爵`一起宣传着解放女性，宣扬女性平等的运动，她们在战乱时期表现出来的那种强大的独立精神让我深深折服。

> “最后，她只得忍气吞声，勉强在一向雇佣女性的行业里寻找机会，并发誓有生之年一定要改变这种不公正的制度。”

当她看到了女性受到不平等待遇的时候，在心底就萌发了要为解放女性而奋斗的决心，在那个战乱的时代，有这种觉悟和追求让我简直是不可置信，作为一个单身妈妈，虽然自己还爱着`菲茨赫伯特伯爵`，但是当她看到`菲茨赫伯特伯爵`反对英国求和的时候，认定`菲茨赫伯特伯爵`是一个冷漠自私的人的时候，她毅然决然地坚定了自己不再爱他的立场，这种理性而又政治立场的态度让我为她着迷。

同样的，`格雷戈里・别斯科夫`也是我比较喜欢的一个男主人公，父母去世后，仍未成年的他担当着抚养弟弟的重任，甚至在弟弟拿着他的梦想跑掉的时候，他还能一如既往地照顾心仪弟弟的`卡捷琳娜`和她的孩子，并且从未变过心，在打仗的时候，照顾`卡捷琳娜`和孩子成为他努力让自己活着的信念。同时，在看到沙皇的暴政的时候，他也是时刻站在苦难群众的立场上，并最终作为领袖成为了推翻沙皇暴政的关键人物。

> “格雷戈里仿佛回到了十二年前。他看见冬宫前面的广场上成百上千的男男女女跪在地上祈祷，对面的士兵端着步枪，他母亲躺倒在地，鲜血在雪地上漫开。他耳边回荡着十一岁列夫的惊叫声：“她死了！妈死了，我母亲死了！”

> “他在战场上学会了先反击，再悲伤”

这些片段深刻地反映了`格雷戈里・别斯科夫`至始至终想为底层苦难群众谋福利的信念，因为他从小就是深受沙皇压迫长大的，他不想后一代人重复他苦难的生活，所以他必须带头革命。

于此同时，由于战争`沃尔特・冯・乌尔里希`和`茉黛・菲茨赫伯特女勋爵`已经有好长时间未见了，在第一部的时候，两人跨越国籍的爱情故事让我唏嘘不已，但是在第二部中，`沃尔特・冯・乌尔里希`因为家人介绍的原因，似乎开始移情别恋。

> “这番碰触就像一丝温暖的电流。两年来没有任何家人之外的女人碰过他。他突然想到，如果能把莫妮卡搂在怀里，让她温暖的身体贴着自己，吻着她的嘴唇，那该多好啊。她那双琥珀色的眼睛坦诚地回应着他的目光，过了一会儿他才发觉，她一定猜出他在想什么了。”

上面这些细节足以说明`沃尔特・冯・乌尔里希`在精神上的出轨，这让我再一次怀疑了这世界上是否存在真正坚定的爱情，当爱情遇到了爱情和家庭的阻挠时，曾经的海誓山盟还有效么，男人似乎永远都是在爱情中容易出轨的那一方，哎，我还能说什么呢。。。

从来只是接触到中国的暴政和战争，在这次通过阅读这本小说了解到外国在战争和战乱时期的人民生活的时候，让我深刻地明白了一个道理：一旦发生战争，受苦的必定是基层人民群众，但是正是这种暴乱的战争生活孕育了伟人的诞生。

这一部总体感觉还是很好的，相比第一部的背景铺垫，这一部结合战争似乎更加让我陷入其中了，期待第三部的故事情节发展。

**Comment by Natumsol** [comment]
比我看得快啊。。。惭愧

**Comment by SunShinewyf** [comment]
@Natumsol ，周日一天看完的，最近入手了一部kindle，估计会更快
