### ISSUE TITLE
你的孤独，虽败犹荣

### ISSUE THREAD

**Issue by SunShinewyf** [SunShinewyf/issue-blog#3]
![images](https://raw.githubusercontent.com/SunShinewyf/issue-blog/master/assets/books/1.jpg)
 近来喜欢看些闲书，于是在周末的临睡前和闲隙看完了这本书。刘同和郭敬明还有韩寒一样，都是用淡淡忧伤的文字触摸人们内心最柔软的轨迹。曾经知道他有一本`《谁的青春不迷茫》`，而且还配有极其文艺的插图，但是单看书名，总觉得是对于青春无奈的一种无病呻吟而已，多少会有一些消极的成分在，而我是最厌恶消极和负面的，所以一直不曾接触过这本书，而这一本，应该更多的是一种激励和共勉吧。事实证明，确实如此。

   书的内容主要是涉及作者本人33岁之前的回忆，通过回忆来剖析和讲解各种孤单，有和父母之间的，上级之间的以及和同龄人之间不被理解的经历，除此之外，还有一些作者遇到的人或者事带给他的关于孤独的思考。孤独呢，有关于爱情，亲情，友情还有同事之情的，可以说，这本书可以称之为一本回忆录。而我最喜欢的就是他回忆毕业后大学同学聚会的场景。他以一种过来人的视角在品味人生，而我却是以一种正在经历的视角在寻找某些雷同。我从不曾想像过毕业10年的班级聚会会是怎样的一番场景，但是我知道时间会改变很多东西，譬如梦想，譬如友谊。很是被里面的一些独具一格的人所感动，包括小五，二毛，都是人群中特立独行的人，在他们的人生轨迹里，诠释着一种`special`。但是青春总是这样匆匆，还来不及回味就已经消失殆尽，只有年龄的不停增长在说明你已经走过了这段最为绚丽的日子。

   >  “在人生的旅途中，回首张望需要勇气，直视而悠长，像是某种神圣的仪式”就像刘同在书中说的，有的时候，回忆需要很大的勇气，无论是那些别人给的伤还是美好，每回想一遍都会引发物是人非的惆怅，与其这样让自己心累，还不如永远没心没肺地一往直前，这样会更显示出一种潇洒。

不知道为什么，很难给孤单下一个定义，不能说独自一人就是孤单，但是之于我，孤单这个词太遥远，无论何时何地，我都有东西陪着，或者是电脑，或者是音乐，即使独自一人。很喜欢里面的一句话：

> 要相信这些年你都能一个人度过所有，当时你恐慌害怕的最终会成为你面对这个世界的盔甲“。

是的，或许你现在正在一个人奋斗着，没有与你并肩作战的人，但是这只是你现在能看到的风景，因为，孤独之前是迷茫，孤独之后就是成长，你用你最好的时光在犯错，那么以后犯的错就会变少，而年龄越大，犯错就越无法被原谅，因为每个人都要经历这些，只是时间早晚的问题。只有学会享受孤独的人才会建立起内心最为强大的精神堡垒，以至于被扔在人流中的时候，可以最早地被别人所看到。

>"30 岁之后，风景于我只是几道走马观花得残影，少有流连忘返的停留”

我不知道，30岁的我会是什么样一番景象，但是我现在可以做到，等那个时候再来回忆这段时光的时候，我可以问心无愧地说：我尽力了。

你的孤独，虽败犹荣，为自己点个赞！！！

**Comment by SunShinewyf** [comment]
读于2015年10月2日

**Comment by JerrodNoliita** [comment]
我觉得你像作者，而我是你的小粉丝

**Comment by SunShinewyf** [comment]
@JerrodNoliita 哈哈，谬赞了~
